# Общие команды python

https://github.com/jakevdp/PythonDataScienceHandbook

### Команда %timeit и %%timeit используется для определения времени  выпонения программы, два знака используются для многострочных команд

‰%time — длительность выполнения отдельного оператора;
‰‰%timeit — длительность выполнения отдельного оператора при неоднократном
повторе, для большей точности;
‰‰%prun — выполнение кода с использованием профилировщика;
‰‰%lprun — пошаговое выполнение кода с применением профилировщика;
‰‰%memit — оценка использования оперативной памяти для отдельного опера- тора;
‰‰%mprun — пошаговое выполнение кода с применением профилировщика па- мяти

In [11]:
%%timeit
a =10;
for i in range(100):
    a +=a
    
%timeit 10**21

6.02 µs ± 44.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [24]:
%time 10**21

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 9.06 µs


1000000000000000000000

In [15]:
# выводят объекты выхода и входа можно выводить последовательность выхода In[1]
print(In)
print(Out)

['', "get_ipython().run_cell_magic('timeit', '', 'for i in range(100):\\n    print(i\\n')", "get_ipython().run_cell_magic('timeit', '', 'for i in range(100):\\n    print(i)\\n')", "get_ipython().run_cell_magic('timeit', '', 'for i in range(100):\\n    print(i)\\n')", "get_ipython().run_cell_magic('timeit', '', 'for i in range(10):\\n    print(i)\\n')", "get_ipython().run_cell_magic('timeit', '', 'a =10;\\nfor i in range(100):\\n    a +=a\\n')", 'get_ipython().run_cell_magic(\'timeit\', \'\', \'a =10;\\nfor i in range(100):\\n    a +=a\\n    \\n%timeit print("r")\\n\')', "get_ipython().run_cell_magic('timeit', '', 'a =10;\\nfor i in range(100):\\n    a +=a\\n    \\n')", "get_ipython().run_cell_magic('timeit', '', 'a =10;\\nfor i in range(100):\\n    a +=a\\n    \\n%timeit 10**21\\n')", "get_ipython().run_cell_magic('timeit', '', 'a =10;\\nfor i in range(100):\\n    a +=a\\n    \\n')", "get_ipython().run_line_magic('timeit', '10**21')", "get_ipython().run_cell_magic('timeit', '', 'a =10;

In [20]:
10+304

314

In [21]:
# предыдущий вывод  так же можно вывести выовод двумя способами Out[2] _2   Out[X] _X
print(_)

314


In [22]:
# можно работать с любыми командыми шела !ls !pwd 
directory = !pwd
directory

['/Users/newlife/Desktop']

In [ ]:
# Отладка
#Если вам необходимо, чтобы отладчик запускался автоматически при 
#генерации исключения, можно воспользоваться «магической» функцией
#%pdb для включения такого автоматического поведения:
%debug


#### Количество занимаемой памяти программой % memit %mprun(работает для функций только)

In [30]:
#
%load_ext memory_profiler
%memit 21**2
%mprun 21**212


The memory_profiler extension is already loaded. To reload it, use:
  %reload_ext memory_profiler
peak memory: 77.61 MiB, increment: 0.00 MiB



# Numpy 


In [63]:
import numpy as np

### Numpy гораздо эффективнее хранит и работает с данными, так как не могут быть в массиве разные типы данных как в list

## Создание массивов

In [64]:
# массив целочисленных значений: 
np.array([1, 4, 2, 5, 3])
# можно задать опредленный тип данных
np.array([1, 2, 3, 4], dtype='float32')

# Вложенные списки преобразуются в многомерный массив 
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
# Создаем массив целых чисел длины 10, заполненный нулями (нулевой массив)
np.zeros(10, dtype=int)

# Создаем массив размером 3 x 5 значений с плавающей точкой, # заполненный единицами
np.ones((3, 5), dtype=float)

# Создаем массив размером 3 x 5, заполненный значением 3.14 
np.full((3, 5), 3.14)

# Создаем массив, заполненный линейной последовательностью, # начинающейся с 0 и заканчивающейся 20, с шагом 2
# (аналогично встроенной функции range())
np.arange(0, 20, 2)

# Создаем массив из пяти значений,
# равномерно располагающихся между 0 и 1 
np.linspace(0, 1, 5)

# Создаем массив размером 3 x 3 равномерно распределенных
# случайных значения от 0 до 1
np.random.random((3, 3))

# Создаем массив размером 3 x 3 нормально распределенных
# случайных значения с медианой 0 и стандартным отклонением 1 
np.random.normal(0, 1, (3, 3))

# Создаем массив размером 3 x 3 случайных целых числа # в промежутке [0, 10)
np.random.randint(0, 10, (3, 3))

# Создаем единичную матрицу размером 3 x 3 
np.eye(3)

# Создаем неинициализированный массив из трех целочисленных
# значений. Значениями будут произвольные, случайно оказавшиеся # в соответствующих ячейках памяти данные
np.empty(3)

# Работа с массивами

In [55]:
import numpy as np
np.random.seed(0) # начальное значение для целей воспроизводимости
x1 = np.random.randint(10, size=6) # одномерный массив 
x2 = np.random.randint(10, size=(3, 4)) # двумерный массив 
x3 = np.random.randint(10, size=(3, 4, 5)) # трехмерный массив

# у каждого массива есть атрибуты
print("x3 ndim: ", x3.ndim) 
print("x3 shape:", x3.shape) 
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
# Другие атрибуты включают itemsize, 
# выводящий размер (в байтах) каждого эле- мента массива, и nbytes,
# выводящий полный размер массива (в байтах):
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")


x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


### Индексация

In [65]:
x2[0, 0]
x2[2, -1]
# замена элемента по индексу
x2[0, 0] = 12

## Срезы
### Срезы массивов возвращают представления (views), а не копии (copies) данных массива. Поэтому если мы возьмем срез и запишем его в переменную и поменяем что то, исходный массив тоже поменятеся! Поэтому нужно польщоваться копиями

   ##### Многомерные срезы задаются схожим образом, с разделением срезов запятыми. Например: x2[:2, :3]

   ###### Измерения подмассивов также можно «переворачивать»: x2[::-1, ::-1]

In [67]:
x = np.arange(10) 

x[1::2] # каждый второй элемент, начиная с индекса 1
x[::2] # каждый второй элемент
x[5::-2] # каждый второй элемент в обратном порядке,начиная с индекса 5


# МНОГОМЕРНЫЕ МАССИВЫ
x2[:2, :3] # две строки три столбца
x2[:3, ::2] # все строки, каждый второй столбец

x2[::-1, ::-1] # перевернуть измерение

print(x2[:, 0]) # первый столбец массива x2
print(x2[0, :]) # первая строка массива x2
print(x2[0]) # эквивалентно x2[0, :]

[12  7  1]
[12  5  2  4]
[12  5  2  4]


## Создание копий массивов

In [ ]:
x2_sub_copy = x2[:2, :2].copy() 
print(x2_sub_copy)

## Изменение формы массивов reshape
Еще одна удобная операция — изменение формы массивов методом reshape(). 
Например, если вам требуется поместить числа от 1 до 9 в таблицу    3 × 3, сделать это можно следующим образом:

In [69]:
x = np.array([1, 2, 3])
# Преобразование в вектор-строку с помощью reshape 
x.reshape((1, 3))

array([[1, 2, 3]])

In [70]:
# Преобразование в вектор-строку посредством newaxis 
x[np.newaxis, :]

array([[1, 2, 3]])

In [71]:
# Преобразование в вектор-столбец с помощью reshape 
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [72]:
# Преобразование в вектор-столбец посредством newaxis 
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Слияние массивов
    - Слияние, или объединение, двух массивов в библиотеке NumPy выполняется в основном с помощью методов np.concatenate, np.vstack и np.hstack. Метод np.concatenate принимает на входе кортеж или список массивов в качестве первого аргумента:

In [74]:
x = np.array([1, 2, 3]) 
y = np.array([3, 2, 1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [75]:
z = [99, 99, 99] 
print(np.concatenate([x, y, z]))


[ 1  2  3  3  2  1 99 99 99]


In [76]:
# слияние двумерных массивов
grid = np.array([[1, 2, 3],
    [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [77]:
# слияние по второй оси координат (с индексом 0) 
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Для работы с массивами с различающимися измерениями удобнее и понятнее использовать функции np.vstack (вертикальное объединение) и np.hstack (гори- зонтальное объединение):

In [80]:
x = np.array([1, 2, 3]) 
grid = np.array([[9, 8, 7],
                [6, 5, 4]])
# Объединяет массивы по вертикали 
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [81]:
# Объединяет массивы по горизонтали 
y = np.array([[99],
             [99]]) 
np.hstack([grid, y])


array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## Разбиение массивов
Противоположностью слияния является разбиение, выполняемое с помощью функций np.split, np.hsplit и np.vsplit. Каждой из них необходимо передавать список индексов, задающих точки раздела:

In [88]:
x = [1, 2, 3, 99, 99, 3, 2, 1] 
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [89]:
grid = np.arange(16).reshape((4, 4)) 
grid


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [91]:
upper, lower = np.vsplit(grid, [2])
print(upper) 
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [92]:
left, right = np.hsplit(grid, [2]) 
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Выполнение вычислений над массивами библиотеки NumPy: универсальные функции


Выполнение вычислений над массивами библиотеки NumPy может быть очень быстрым и очень медленным. Ключ к их ускорению — использование вектори- зованных операций, обычно реализуемых посредством универсальных функций (universal functions, ufuncs) языка Python. В данном разделе будет обосновано, почему универсальные функции библиотеки NumPy необходимы и почему они могут намного ускорить выполнение повторяющихся вычислений над элементами массивов, а также познакомим вас с множеством наиболее распространенных и по- лезных универсальных арифметических функций из библиотеки NumPy.

### Чтобы операции быле быстрее лучше выполнять команды для массивов, а не для элементов
пример-

In [ ]:
print(compute_reciprocals(values)) 
print(1.0 / values) # так не нужно!!!

# надо так!
np.arange(5) / np.arange(1, 6) # операция с массивами
x = np.arange(9).reshape((3, 3)) 
2 ** x

In [ ]:
x = np.arange(4)
print("x = ",x)
print("x + 5", x+5)
print("x - 5", x-5)
print("x * 2", x*2)
print("x / 2 =", x/2)
print("x // 2 =", x // 2) # деление с округлением в меньшую сторону


#Существует также унарная универсальная функция для операции изменения знака, 
# оператор ** для возведения в степень и оператор % для деления по модулю:

print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

# Дополнительно эти операции можно комбинировать любыми способами 
# с соблюением стандартного приоритета выполнения операций: